### ISSUE TITLE
guide.rnbw.dev enhancements

### ISSUE THREAD

**Issue by edenvidal** [rnbwdev/rnbw-guide#4]
add about live sync - " Files are responsive to local changes and fetch them, allowing for real-time updates of the active page while retaining the focus on the active element."

@atulbhatt-system32 :

- [x] in #code - to align the codeview
- [x]  seo: optimize for search engine visibility.

**Comment by atulbhatt-system32** [comment]
@edenvidal, the codeview is in rnbw-preview web component which comes from rnbw.company where the codeview is aligned. So once the rnbw.company dev branch changes are in main it will work.

**Comment by atulbhatt-system32** [comment]
@edenvidal how do you want the #code to be aligned

**Comment by edenvidal** [comment]
<img width="1432" alt="Screenshot 2024-01-30 at 14 50 45" src="https://github.com/rnbwdev/rnbw-guide/assets/13418616/77fc4a78-0e76-41d5-a3d4-2e3458f691bd">
